version: '3'
services:
  postgres:
    container_name: postgres
    image: postgres:14
    hostname: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      POSTGRES_DB: ${POSTGRES_DBNAME:-postgres}
      PGDATA: /data/postgres
    volumes:
      - pg-data:/data/postgres
    ports:
      - '5432:5432'
    networks:
      - dev_network
    restart: always
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -d postgres -U postgres']
      interval: 5s
      timeout: 5s
      retries: 15

networks:
  dev_network:
    name: dev_network
    driver: bridge

volumes:
  pg-data:
