services:
  # A Docker web service
  - type: web
    name: website
    env: node
    region: oregon
    plan: standard
    branch: main
    buildCommand: npm install && npm run build
    runCommand: node build/index.js
    pullRequestPreviewsEnabled: true
    buildFilter:
      paths:
        - src/**/*.js
      ignoredPaths:
        - src/**/*.test.js
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: database
          property: connectionString
      - key: SMTP_SERVER
        sync: false
      - key: SMTP_PORT
        value: 587
      - key: SMTP_LOGIN
        sync: false
      - key: SMTP_PASSWORD
        sync: false
      - key: BASE_URL
        value: https://www.octopuzzles.com
      - key: JWT_SECRET
        generateValue: true

databases:
  - name: database
    databaseName: octopuzzles
    user: octopuzzles
    ipAllowList: [] # only allow internal connections
