previewsEnabled: true
previewsExpireAfterDays: 3
services:
  - type: web
    name: website
    env: node
    region: oregon
    plan: standard
    previewPlan: starter
    buildCommand: npm install && npm run generate && npx run db:migrate:deploy && npm run build
    startCommand: node apps/website/build/index.js
    pullRequestPreviewsEnabled: true
    initialDeployHook: npm run db:seed
    buildFilter:
      paths:
        - ./**/*.svelte
        - ./**/*.ts
        - ./**/*.html
      ignoredPaths:
        - ./**/*.test.js
        - ./**/tests/**/*.ts
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: database
          property: connectionString
      - key: SMTP_SERVER
        sync: false
      - key: SMTP_PORT
        value: 587
      - key: SMTP_LOGIN
        sync: false
      - key: SMTP_PASSWORD
        sync: false
      - key: BASE_URL
        value: https://www.octopuzzles.com
        previewValue: REPLACE_ME
      - key: JWT_SECRET
        generateValue: true

databases:
  - name: database
    databaseName: octopuzzles
    user: octopuzzles
    plan: starter
    previewPlan: starter
    ipAllowList: []
