name: lintingAndPrettier
# Controls when the workflow will run
on:
  pull_request:
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install modules
        run: npm i
      - name: Run Prettier
        run: npm run format:check
      - name: Run ESLint
        run: npm run lint
